server:
  port: 80
swagger:
  base-package: com.laozhu
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud_db01?serverTimezone=GMT%2B8 # 数据库名称
#    url: jdbc:mysql://192.168.31.242:3306/springcloud_db01?serverTimezone=GMT%2B8 # 数据库名称
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
#    url: jdbc:oracle:thin:@192.168.31.242:1521:helowin # 数据库名称
#    username: zhy
#    password: zhy
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
          # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 150 # 等待连接获取的最大超时时间
  application:
    name: microservice-consumer

eureka:
  client:
    register-with-eureka: false #服务注册开关
    fetch-registry: true
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
